<Project>

  <PropertyGroup Label="Build">
    <!-- GitHub Actions sets $(CI) -->
    <ContinuousIntegrationBuild Condition="'$(CI)' != ''">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Label="Language">
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Label="Analyzers">
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup Label="Output">
    <RepositoryRoot>$(MSBuildThisFileDirectory)</RepositoryRoot>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <PackageOutputPath>$(RepositoryRoot)artifacts/nupkg</PackageOutputPath>
  </PropertyGroup>

  <PropertyGroup Label="Shared package metadata">
    <Authors>Stefan Greve</Authors>
    <Copyright>Copyright (c) 2026 Stefan Greve</Copyright>
    <Version>0.1.0-alpha.1</Version>
  </PropertyGroup>

</Project>
