blank_issues_enabled: false

contact_links:
  - name: Share an idea
    url: https://github.com/StefanGreve/gelyn/discussions/categories/ideas
    about: Float an idea before opening a feature request.
